language: node_js
node_js:
  - lts/*

before_script:
  - yarn
  - yarn global add codecov

script:
  - yarn build
  - yarn lint:fix
  - yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: never
